import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// PLACEHOLDER — this file must be regenerated before Firebase will work.
///
/// This is normally auto-generated by the FlutterFire CLI (`flutterfire
/// configure`), which reads your actual Firebase project and fills in real
/// values for every platform. I can't run that here (no access to
/// console.firebase.google.com or your Google account from this
/// environment), so this stub exists only so the project *compiles* — every
/// value below is a placeholder and Firebase will fail to initialize until
/// you replace this file. See FIREBASE_SETUP.md for the exact steps.
///
/// The shape of this file (DefaultFirebaseOptions.currentPlatform, per-
/// platform static options) matches exactly what `flutterfire configure`
/// generates, so running that command will simply overwrite this file with
/// working values — no other code needs to change.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run `flutterfire configure` to add it.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_WEB_API_KEY',
    appId: 'REPLACE_WITH_YOUR_WEB_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    databaseURL: 'https://REPLACE_WITH_YOUR_PROJECT_ID-default-rtdb.firebaseio.com',
    storageBucket: 'REPLACE_WITH_YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ4PpuWN2pA9kqWKvWtoGAFbEONZ8UZYA',
    appId: '1:58548553120:android:f3a29ad359eabfccfb50c5',
    messagingSenderId: '58548553120',
    projectId: 'studentfoodservice-82f3b',
    databaseURL: 'https://studentfoodservice-82f3b-default-rtdb.firebaseio.com',
    storageBucket: 'studentfoodservice-82f3b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_IOS_API_KEY',
    appId: 'REPLACE_WITH_YOUR_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    databaseURL: 'https://REPLACE_WITH_YOUR_PROJECT_ID-default-rtdb.firebaseio.com',
    iosBundleId: 'com.example.aiAssist',
  );

  /// True once this file has been regenerated with real values — used by
  /// main.dart to decide whether to even attempt Firebase.initializeApp(),
  /// so a fresh checkout doesn't show a scary SDK error before you've had a
  /// chance to run flutterfire configure.
  static bool get isConfigured => !currentPlatform.apiKey.startsWith('REPLACE_WITH_');
}
