// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// PLACEHOLDER — DO NOT USE AS-IS.
///
/// This file is normally auto-generated by running:
///
///   dart pub global activate flutterfire_cli
///   flutterfire configure
///
/// against your own Firebase project. That command overwrites this file
/// with real apiKey/appId/projectId values for Android/iOS/Web. The
/// values below are structurally valid but non-functional placeholders
/// so the project compiles before you've run flutterfire configure.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run `flutterfire configure` to generate them.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    authDomain: 'REPLACE_ME.firebaseapp.com',
    databaseURL: 'https://REPLACE_ME-default-rtdb.firebaseio.com',
    storageBucket: 'REPLACE_ME.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ4PpuWN2pA9kqWKvWtoGAFbEONZ8UZYA',
    appId: '1:58548553120:android:ce44f78487fb9574fb50c5',
    messagingSenderId: '58548553120',
    projectId: 'studentfoodservice-82f3b',
    databaseURL: 'https://studentfoodservice-82f3b-default-rtdb.firebaseio.com',
    storageBucket: 'studentfoodservice-82f3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    databaseURL: 'https://REPLACE_ME-default-rtdb.firebaseio.com',
    storageBucket: 'REPLACE_ME.appspot.com',
    iosBundleId: 'com.example.interiorArApp',
  );
}